name: container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    container:
      image: node:latest
    steps:
      - name: log node node-version
        run: |
          node -v
          cat /etc/os-release 
